const girl = [
    {
        group:"BLACKPINK",
        img:"./blackpink.jpg",
        price:"$64.99",
        gen:"3rd Generation",
        company:"YG",
    },
    {
        group:"IVE",
        img:"./ive.png",
        price:"$54.99",
        gen:"4th Generation",
        company:"Starship",
    },
    {
        group:"LE SSERAFIM",
        img:"./LESSIRAFIM.png",
        price:"$79.99",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"NEWJEANS ",
        img:"./newjeans.png",
        price:" $69.99",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"KEP1LER",
        img:"./kep1ler.png",
        price:"$59.99",
        gen:"4th Generation",
        company:"WakeOne",
    },
    {
        group:"AESPA",
        img:"./aespa.png",
        price:" $59.99",
        gen:"4th Generation",
        company:"SM",
    },
    {
        group:"(G)I-DLE",
        img:"./gilde.png",
        price:"$59.99",
        gen:"4th Generation",
        company:"Cube",
    },
    {
        group:"LOONA",
        img:"./loona.png",
        price:"$64.99",
        gen:"4th Generation",
        company:"BBC",
    },
    {
        group:"STAYC",
        img:"./stayc.png",
        price:"$69.99",
        gen:"4th Generation",
        company:"High Up",
    },
    {
        group:"WEKI MEKI",
        img:"./WEKI-MEKI.png",
        price:"$55.99",
        gen:"4th Generation",
        company:"Fantagio",
    },
]
const boy = [
    {
        group:"SEVENTEEN",
        img:"./seventeen.png",
        price:"$69.99",
        gen:"3rd Generation",
        company:"HYBE",
    },
    {
        group:"ATEEZ",
        img:"./ateez.png",
        price:"$59.99",
        gen:"4th Generation",
        company:"KQ",
    },
    {
        group:"STRAY KIDS",
        img:"./straykids.jpg",
        price:"$62.99",
        gen:"4th Generation",
        company:"JYP",
    },
    {
        group:"THE BOYZ",
        img:"./theboyz.png",
        price:"$59.99",
        gen:"4th Generation",
        company:"IST",
    },
    {
        group:"ENHYPEN",
        img:"./enhypen.png",
        price:"$69.99",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"TREASURE",
        img:"./treasure.png",
        price:"$53.99",
        gen:"4th Generation",
        company:"YG",
    },
    {
        group:"ZEROBASEONE",
        img:"./zb1.png",
        price:"$65.99",
        gen:"5th Generation",
        company:"WakeOne",
    },
    {
        group:"GOT7",
        img:"./got7.png",
        price:"$59.99",
        gen:"3rd Generation",
        company:"JYP",
    },
    {
        group:"CRAVITY",
        img:"./cravity.png",
        price:"$57.99",
        gen:"4th Generation",
        company:"Starship",
    },
    {
        group:"MONSTA X",
        img:"./monsta-x.png",
        price:"$59.99",
        gen:"3rd Generation",
        company:"Starship",
    },
];
export {girl, boy};