const menu = [
    {
        group:"BLACKPINK",
        img:"./blackpink.jpg",
        price:"$64.99",
        bg:"Girl Group",
        gen:"3rd Generation",
        company:"YG",
    },
    {
        group:"IVE",
        img:"./ive.png",
        price:"$54.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"Starship",
    },
    {
        group:"LE SSERAFIM",
        img:"./LESSIRAFIM.png",
        price:"$79.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"NEWJEANS ",
        img:"./newjeans.png",
        price:"$69.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"KEP1LER",
        img:"./kep1ler.png",
        price:"$59.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"WakeOne",
    },
    {
        group:"AESPA",
        img:"./aespa.png",
        price:" $59.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"SM",
    },
    {
        group:"(G)I-DLE",
        img:"./gilde.png",
        price:"$59.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"CUBE",
    },
    {
        group:"RED VELVET",
        img:"./redvelvet.jpg",
        price:"$64.99",
        bg:"Girl Group",
        gen:"3rd Generation",
        company:"SM",
    },
    {
        group:"NMIXX",
        img:"./nmixx.jpg",
        price:"$79.99",
        bg:"Girl Group",
        gen:"4th Generation",
        company:"JYP",
    },
    {
        group:"TWICE",
        img:"./twice.jpg",
        price:"$64.99",
        bg:"Girl Group",
        gen:"3rd Generation",
        company:"JYP",
    },
    {
        group:"SEVENTEEN",
        img:"./seventeen.jpg",
        price:"$69.99",
        bg:"Boy Group",
        gen:"3rd Generation",
        company:"HYBE",
    },
    {
        group:"ATEEZ",
        img:"./ateez.png",
        price:"$59.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"KQ",
    },
    {
        group:"STRAY KIDS",
        img:"./straykids.jpg",
        price:"$62.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"JYP",
    },
    {
        group:"THE BOYZ",
        img:"./theboyz.png",
        price:"$59.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"IST",
    },
    {
        group:"ENHYPEN",
        img:"./enhypen.png",
        price:"$69.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"HYBE",
    },
    {
        group:"TREASURE",
        img:"./treasure.png",
        price:"$53.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"YG",
    },
    {
        group:"EXO",
        img:"./exo.jpg",
        price:"$55.99",
        bg:"Boy Group",
        gen:"3rd Generation",
        company:"SM",
    },
    {
        group:"GOT7",
        img:"./got7.png",
        price:"$59.99",
        bg:"Boy Group",
        gen:"3rd Generation",
        company:"JYP",
    },
    {
        group:"CRAVITY",
        img:"./cravity.png",
        price:"$57.99",
        bg:"Boy Group",
        gen:"4th Generation",
        company:"Starship",
    },
    {
        group:"MONSTA X",
        img:"./monsta-x.png",
        price:"$59.99",
        bg:"Boy Group",
        gen:"3rd Generation",
        company:"Starship",
    },
]
export {menu};